# This script is used to precompile vignettes and should be run for
# each new version of the package

# Get current wd (to restore later)
old_wd <- getwd()
# Set wd to vignettes to avoid saving to base directory
setwd("vignettes/")
# Precompile vignettes
library(knitr)
knit("./.source/rredlist.Rmd", "rredlist.Rmd")

# Build vignettes
library(devtools)
build_vignettes()

# x = vignette file name including file extension (e.g. "rredlist.Rmd")
read_only <- function(x) {
  tmp <- file(x)
  writeLines(c(
    paste0("% Generated by vignettes/precompile.R: do not edit by hand.\n",
           "% Please edit source in vignettes/.source/", x),
    readLines(x)), tmp)
  close(tmp)
}
# Add read only info
read_only("rredlist.Rmd")
rm(read_only)

# Restore wd
setwd(old_wd)
